name: "Publish Spz.NET"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Publish version'
        required: true
  release:
    types: [published]


jobs:
  publish:
    env:
      VERSION: ${{ github.event.release.tag_name || github.event.inputs.version }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build
        working-directory: ./Spz.NET
        run: dotnet pack -c Release -p:Version=${{ env.VERSION }} -p:PackageVersion=${{ env.VERSION }}

      - name: Nuget Publish
        working-directory: ./Spz.NET
        run: dotnet nuget push ./bin/Release/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
